name: vodiy_soft
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.3


  #UI
  cupertino_icons: ^1.0.2

  # MAP
  google_maps_flutter: ^2.5.3
  geolocator: ^7.0.3

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  get_it: ^7.6.0

  #NERWORK
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  http: ^1.1.0
  retrofit: ^4.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  #DB
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/png/
    - assets/svg/
    - assets/jpg/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
